# Generated by Django 4.2 on 2023-04-06 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_no', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.TextField(max_length=200)),
                ('room_price', models.IntegerField(default=0)),
                ('room_status', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='flat_no',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Defined', 'Not Defined')], default='Not Defined', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_status', models.TextField(choices=[('Check In', 'Checked In'), ('Check Out', 'Checked Out'), ('Hold', 'On Hold')], default='On Hold', max_length=40)),
                ('room_link', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.rooms', verbose_name='Room No')),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
