# Generated by Django 4.2 on 2023-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rooms_customuser_age_customuser_area_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(max_length=150),
        ),
    ]
