# Generated by Django 4.2 on 2023-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_gender"),
    ]

    operations = [
        migrations.RemoveField(model_name="rooms", name="room_status",),
        migrations.AddField(
            model_name="rooms",
            name="room_available",
            field=models.BooleanField(default=True),
        ),
    ]
