# Generated by Django 4.2 on 2023-04-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_gender"),
    ]

    operations = [
        migrations.DeleteModel(name="Reservation",),
        migrations.DeleteModel(name="Rooms",),
    ]
