# Generated by Django 4.2 on 2023-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "room_no",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Room No"
                    ),
                ),
                ("room_type", models.TextField(max_length=200)),
                ("room_price", models.IntegerField(default=0)),
                ("room_available", models.BooleanField(default=True)),
            ],
        ),
    ]
