# Generated by Django 4.2 on 2023-04-24 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0002_alter_rooms_room_no_alter_rooms_room_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_status",
                    models.TextField(
                        choices=[
                            ("Check In", "Checked In"),
                            ("Check Out", "Checked Out"),
                            ("Hold", "On Hold"),
                        ],
                        default="On Hold",
                        max_length=40,
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booked_room",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooms.rooms",
                        verbose_name="Room No",
                    ),
                ),
            ],
        ),
    ]
